#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

sleep 30
exec 2> /tmp/rc.local.debug
set -x
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
  sudo python /home/pi/scripts/startup_mailer.py # don't actually need sudo
#else
  # nothing really, I've stripped out some other function which is then called
fi
exit 0
